[2023-12-10T17:28:39.024+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.extract_data manual__2023-12-10T12:23:18.002625+00:00 [queued]>
[2023-12-10T17:28:39.049+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.extract_data manual__2023-12-10T12:23:18.002625+00:00 [queued]>
[2023-12-10T17:28:39.049+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-10T17:28:39.083+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract_data> on 2023-12-10 12:23:18.002625+00:00
[2023-12-10T17:28:39.094+0500] {standard_task_runner.py:57} INFO - Started process 6963 to run task
[2023-12-10T17:28:39.110+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'extract_data', 'manual__2023-12-10T12:23:18.002625+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmph5mcmx72']
[2023-12-10T17:28:39.115+0500] {standard_task_runner.py:85} INFO - Job 7: Subtask extract_data
[2023-12-10T17:28:39.196+0500] {task_command.py:416} INFO - Running <TaskInstance: test.extract_data manual__2023-12-10T12:23:18.002625+00:00 [running]> on host xypma-VirtualBox
[2023-12-10T17:28:39.342+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='test' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T12:23:18.002625+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-10T12:23:18.002625+00:00'
[2023-12-10T17:28:39.343+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-10T17:28:39.348+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir data && cd data && mkdir raw && unzip -o -q /home/xypma/lab3/MLOps_lab3/datasets/data.zip -d /home/xypma/lab3/MLOps_lab3/datasets/data/raw/']
[2023-12-10T17:28:39.358+0500] {subprocess.py:86} INFO - Output:
[2023-12-10T17:28:39.365+0500] {subprocess.py:93} INFO - checkdir:  cannot create extraction directory: /home/xypma/lab3/MLOps_lab3/datasets/data/raw
[2023-12-10T17:28:39.366+0500] {subprocess.py:93} INFO -            No such file or directory
[2023-12-10T17:28:39.366+0500] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-10T17:28:39.378+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/xypma/lab3/MLOps_lab3/virt/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-10T17:28:39.386+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test, task_id=extract_data, execution_date=20231210T122318, start_date=20231210T122839, end_date=20231210T122839
[2023-12-10T17:28:39.409+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task extract_data (Bash command failed. The command returned a non-zero exit code 2.; 6963)
[2023-12-10T17:28:39.424+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-10T17:28:39.502+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
